stateDiagram-v2
    [*] --> Idle_false
    Idle_false: Idle(false)
    Idle_true: Idle(true)
    Busy_false: Busy(false)
    Busy_true: Busy(true)
    ProcessingCommand: ProcessingCommand
    WaitForCommandCompleteAck: WaitForCommandCompleteAck
    WaitForAsyncEventAck: WaitForAsyncEventAck

    Idle_false --> ProcessingCommand: SetNotificationEnable [ExecuteCommand]
    Idle_false --> Busy_false: BusyChanged
    Idle_false --> Idle_false: PpmReset [ResetComplete]

    Busy_false --> Idle_false: BusyChanged
    Busy_false --> Busy_false: CommandComplete
    Busy_false --> Idle_false: PpmReset [ResetComplete]

    Idle_true --> Busy_true: BusyChanged
    Idle_true --> WaitForAsyncEventAck: PendingAsyncEvent [OpmNotifyAsyncEvent]
    Idle_true --> ProcessingCommand: Command [ExecuteCommand]
    Idle_true --> Idle_false: PpmReset [ResetComplete]

    Busy_true --> Idle_true: BusyChanged
    Busy_true --> Busy_true: CommandComplete [OpmNotifyBusy]
    Busy_true --> Busy_true: CommandComplete
    Busy_true --> Idle_false: PpmReset [ResetComplete]

    ProcessingCommand --> WaitForCommandCompleteAck: CommandComplete [OpmNotifyCommandComplete]
    ProcessingCommand --> WaitForCommandCompleteAck: Cancel [OpmNotifyCommandComplete]
    ProcessingCommand --> Idle_false: PpmReset [ResetComplete]

    WaitForCommandCompleteAck --> Idle_true: AckCcCi [OpmNotifyAckComplete]
    WaitForCommandCompleteAck --> Idle_false: PpmReset [ResetComplete]

    WaitForAsyncEventAck --> Idle_true: AckCcCi
    WaitForAsyncEventAck --> Idle_false: PpmReset [ResetComplete]
