stateDiagram-v2
    [*] --> Idle(false)
    Idle(false) --> Idle(true): NotificationEnabled
    Idle(false) --> Busy(false): BusyChanged
    Idle(false) --> Idle(false): CommandImmediate
    Idle(false) --> Idle(false): CommandAsync
    Busy(false) --> Idle(false): BusyChanged
    Busy(false) --> Busy(false): CommandImmediate
    Busy(false) --> Busy(false): CommandAsync
    Idle(true) --> Busy(true): BusyChanged
    Idle(true) --> WaitForAsyncEventAck: PendingAsyncEvent [OpmNotifyAsyncEvent]
    Idle(true) --> WaitForCommandCompleteAck: CommandImmediate [OpmNotifyCommandComplete]
    Idle(true) --> ProcessingCommand: CommandAsync [OpmNotifyBusy]
    Busy(true) --> Idle(true): BusyChanged
    Busy(true) --> Busy(true): CommandImmediate [OpmNotifyBusy]
    Busy(true) --> Busy(true): CommandAsync [OpmNotifyBusy]
    ProcessingCommand --> WaitForCommandCompleteAck: CommandCompleted [OpmNotifyCommandComplete]
    ProcessingCommand --> WaitForCommandCompleteAck: Cancel [OpmNotifyCommandComplete]
    WaitForCommandCompleteAck --> Idle(true): CommandCompleteAck
    WaitForAsyncEventAck --> Idle(true): AsyncEventAck
    WaitForAsyncEventAck --> WaitForCommandCompleteAck: CommandImmediate [OpmNotifyCommandComplete]
    WaitForAsyncEventAck --> ProcessingCommand: CommandAsync [OpmNotifyBusy]
    Idle(false) --> Idle(false): Reset [OpmNotifyReset]
    Busy(false) --> Idle(false): Reset [OpmNotifyReset]
    Idle(true) --> Idle(false): Reset [OpmNotifyReset]
    Busy(true) --> Idle(false): Reset [OpmNotifyReset]
    ProcessingCommand --> Idle(false): Reset [OpmNotifyReset]
    WaitForCommandCompleteAck --> Idle(false): Reset [OpmNotifyReset]
    WaitForAsyncEventAck --> Idle(false): Reset [OpmNotifyReset]